### ISSUE TITLE
Moon Cache Not Auto Expanding

### ISSUE THREAD

**Issue by jvandag** [aberoth-community/ephemeris-discord-bot#2]
The bot does not recompute the cache to expand the range of the moon cycle cache when requesting events outside of the current cache's range like it does with the scroll cache.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the getPhaseList function in helperFuncs.py to recompute the moon cycle cache when requesting events outside the current cache range. This brings its behavior in line with how the scroll cache is handled.

You can review changes in this commit: https://github.com/lkilu6456546/aberoth-community-ephemeris-discord-bot-2/commit/653de09474e31c678a1b96b8bb0c8416d0e614b9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jvandag** [comment]
Fixed with commit [601043b](https://github.com/aberoth-community/ephemeris-discord-bot/commit/601043bf370ecbf55e60f50ed51c71b39f88494b)
